server:
  port: 8076
spring:
  application:
    name: token-service
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 49.233.171.48:8848
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

#验证码开关
validCode:
   flag: false
   timeout: 60