server:
  port: 8076
spring:
  application:
    name: token-service
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #redis
  redis:
    host: 139.199.89.237
    port: 6380

#验证码开关
validCode:
  flag: false
  timeout: 60