server:
  port: 8074
spring:
  application:
    name: transmit-request
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848